# Generated by Django 5.2.7 on 2025-11-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_published_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
